# base image to use for the application
FROM python:3.12  

# set the working directory in the container
WORKDIR /apps

# copy the requirements file to the working directory
COPY requirements.txt .

# update the package list and install dependencies
RUN apt-get update 

# install the dependencies specified in the requirements file
RUN pip install --no-cache-dir -r requirements.txt 

# copy the application code to the working directory
COPY . .

# expose the port that the application will run on
EXPOSE 8000

# set the command to run the application
CMD [ "python", "main.py" ]